import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const TRIVIAL_VERB_STEMS =
	"Import|Defin|Initializ|Setting|Set\\s+up|Setup|Return|Check|Loop|Iterat|Creat|Updat|Delet|Remov|Handl|Get|Fetch|Increment|Decrement|Writ|Runn|Run|Pars|Execut|Extract|Sav|Load|Build|Start|Stopp|Stop|Clean(?:up|\\s+up)?|Configur|Validat|Process|Queue|Fire|Emit|Dispatch|Log|Print|Render";

const TRIVIAL_JS_COMMENT_PATTERNS = [
	// "This function does X" when the declaration name already says X
	/\/\/\s*This (?:function|method|class|variable|constant) (?:will |is used to |is responsible for )?/i,
	// "Verb[ing/s] ..." or bare "// Verb" imperative.
	new RegExp(`\\/\\/\\s*(?:${TRIVIAL_VERB_STEMS})(?:e|es|ing|s)?\\b`, "i"),
];

const TRIVIAL_PYTHON_COMMENT_PATTERNS = [
	/^#\s*This (?:function|method|class) (?:will |is used to )?/i,
	new RegExp(`^#\\s*(?:${TRIVIAL_VERB_STEMS})(?:e|es|ing|s)?\\b`, "i"),
];

// Keywords that indicate a comment is explanatory / meaningful
const EXPLANATORY_KEYWORDS =
	/\b(?:because|since|note|todo|fixme|hack|warn|warning|workaround|caveat|important|assumes?)\b/i;

// Characters that suggest commented-out code rather than prose
const COMMENTED_CODE_CHARS = /[({=;}\]>]/;

const MAX_TRIVIAL_COMMENT_LENGTH = 60;

const isJsComment = (trimmed: string): boolean =>
	trimmed.startsWith("//") && !trimmed.startsWith("///") && !trimmed.startsWith("//!");
const isPythonComment = (trimmed: string): boolean =>
	trimmed.startsWith("#") && !trimmed.startsWith("#!");

/**
 * Extract just the comment text after the comment marker.
 */
const getCommentBody = (trimmed: string): string => {
	if (trimmed.startsWith("//")) return trimmed.slice(2).trim();
	if (trimmed.startsWith("#")) return trimmed.slice(1).trim();
	return trimmed;
};

const isTrivialComment = (trimmed: string, nextLine: string | undefined): boolean => {
	const isJs = isJsComment(trimmed);
	const isPy = isPythonComment(trimmed);
	if (!isJs && !isPy) return false;

	const commentBody = getCommentBody(trimmed);

	// Skip long comments — they likely contain meaningful context
	if (commentBody.length > MAX_TRIVIAL_COMMENT_LENGTH) return false;

	// Skip comments with explanatory keywords
	if (EXPLANATORY_KEYWORDS.test(commentBody)) return false;

	// Skip parenthetical explanations like "(excluding ignored directories)"
	if (commentBody.includes("(") && commentBody.includes(")")) return false;

	// Skip commented-out code (contains code-like characters)
	if (COMMENTED_CODE_CHARS.test(commentBody)) return false;

	// Skip section dividers (followed by a blank line)
	if (nextLine !== undefined && nextLine.trim() === "") return false;

	// Skip section divider / header comments (contain box-drawing or repeated dashes)
	if (/[─━═╌╍┄┅│┃]/.test(commentBody)) return false;
	if (/^-{3,}|─{3,}/.test(commentBody)) return false;

	// Now check against the actual trivial patterns
	const patterns = isJs ? TRIVIAL_JS_COMMENT_PATTERNS : TRIVIAL_PYTHON_COMMENT_PATTERNS;
	return patterns.some((pattern) => pattern.test(trimmed));
};

const scanFileForTrivialComments = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");
	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		const nextLine = i + 1 < lines.length ? lines[i + 1] : undefined;
		if (!isTrivialComment(trimmed, nextLine)) continue;
		diagnostics.push({
			filePath: relativePath,
			engine: "ai-slop",
			rule: "ai-slop/trivial-comment",
			severity: "warning",
			message: "Trivial comment that restates the code",
			help: "Remove comments that don't add information beyond what the code already expresses",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: true,
		});
	}
	return diagnostics;
};

export const detectTrivialComments = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		const relativePath = path.relative(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		diagnostics.push(...scanFileForTrivialComments(content, relativePath));
	}

	return diagnostics;
};
