// aislop-ignore-file duplicate-block
import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const CONSOLE_LOG_PATTERN = /\bconsole\.(?:log|debug|info|trace|dir|table)\s*\(/;

const slop = (
	filePath: string,
	line: number,
	rule: string,
	severity: Diagnostic["severity"],
	message: string,
	help: string,
	fixable: boolean,
): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule,
	severity,
	message,
	help,
	line,
	column: 0,
	category: "AI Slop",
	fixable,
});

const LOGGER_FILE_PATTERN = /(?:^|\/)(?:logger|logging|log)\.[^/]+$/i;

const detectConsoleLeftovers = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	if (!JS_EXTENSIONS.has(ext)) return [];

	if (LOGGER_FILE_PATTERN.test(relativePath)) return [];
	if (isNonProductionPath(relativePath)) return [];

	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		if (CONSOLE_LOG_PATTERN.test(trimmed)) {
			if (/console\.(?:error|warn)\s*\(/.test(trimmed)) continue;
			// Skip JSON output patterns like console.log(JSON.stringify(...))
			if (/console\.log\(\s*JSON\.stringify\b/.test(trimmed)) continue;

			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/console-leftover",
					"warning",
					"console.log/debug/info statement left in production code",
					"Remove debugging console statements or replace with a proper logger",
					true,
				),
			);
		}
	}

	return diagnostics;
};

// Build patterns with concatenation so this file doesn't trigger its own rules
const todoKeywords = ["TO" + "DO", "FIX" + "ME", "HA" + "CK", "XX" + "X"];
const markerKeywords = ["TE" + "MP", "PLACEHO" + "LDER", "ST" + "UB"];
const TODO_PATTERN = new RegExp(
	`\\b(?:${todoKeywords.join("|")})\\b[:\\s]|\\b(?:${markerKeywords.join("|")})[:\\s]`,
);

const detectTodoStubs = (content: string, relativePath: string): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		if (
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("#") &&
			!trimmed.startsWith("*") &&
			!trimmed.startsWith("/*")
		) {
			continue;
		}

		if (TODO_PATTERN.test(trimmed)) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/todo-stub",
					"info",
					"Unresolved TODO/FIXME/HACK comment indicates incomplete code",
					"Resolve the TODO or create a tracked issue for it",
					false,
				),
			);
		}
	}

	return diagnostics;
};

const detectDeadCodePatterns = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		const nextLine = i + 1 < lines.length ? lines[i + 1]?.trim() : undefined;

		// Unreachable code after return/throw — but not before }, //, /*, case, default, if, else
		if (
			JS_EXTENSIONS.has(ext) &&
			/^(?:return|throw)\b/.test(trimmed) &&
			trimmed.endsWith(";") &&
			nextLine &&
			nextLine.length > 0 &&
			!nextLine.startsWith("}") &&
			!nextLine.startsWith("//") &&
			!nextLine.startsWith("/*") &&
			!nextLine.startsWith("case ") &&
			!nextLine.startsWith("default:") &&
			!nextLine.startsWith("if ") &&
			!nextLine.startsWith("if(") &&
			!nextLine.startsWith("else")
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 2,
					"ai-slop/unreachable-code",
					"warning",
					"Code after return/throw statement is unreachable",
					"Remove the unreachable code or restructure the control flow",
					false,
				),
			);
		}

		// Constant conditions — but skip lines that are inside strings or regex patterns
		if (
			/\bif\s*\(\s*(?:false|true|0|1)\s*\)/.test(trimmed) &&
			!trimmed.startsWith("//") &&
			!trimmed.startsWith("*") &&
			!/["'`].*\bif\s*\(/.test(trimmed) &&
			!/\/.*\bif\s*\(/.test(trimmed.replace(/\/\/.*$/, ""))
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/constant-condition",
					"warning",
					"Conditional with a constant value — likely debugging leftover",
					"Remove the constant condition or replace with proper logic",
					false,
				),
			);
		}

		if (
			JS_EXTENSIONS.has(ext) &&
			/(?:function\s+\w+|=>\s*)\s*\{\s*\}\s*;?\s*$/.test(trimmed) &&
			!trimmed.startsWith("interface") &&
			!trimmed.startsWith("type ")
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/empty-function",
					"info",
					"Empty function body — possible stub or unfinished implementation",
					"Implement the function body or add a comment explaining why it's empty",
					false,
				),
			);
		}
	}

	return diagnostics;
};

// Build regex patterns with concatenation to avoid self-detection
const asAnyPattern = new RegExp(`\\b${"a" + "s"}\\s+${"an" + "y"}\\b`);
const doubleAssertPattern = new RegExp(`\\b${"a" + "s"}\\s+${"unkn" + "own"}\\s+${"a" + "s"}\\s+`);

const detectUnsafeTypePatterns = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	if (ext !== ".ts" && ext !== ".tsx") return [];
	if (isNonProductionPath(relativePath)) return [];

	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();

		// Check ts-directives BEFORE skipping comments, since @ts-ignore IS a comment
		if (
			/\/\/\s*@ts-(?:ignore|expect-error)/.test(trimmed) ||
			/\/\*\s*@ts-(?:ignore|expect-error)/.test(trimmed)
		) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/ts-directive",
					"info",
					"@ts-ignore/@ts-expect-error suppresses type checking — review if still needed",
					"Fix the underlying type issue instead of suppressing the error",
					false,
				),
			);
		}

		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		// Skip lines that are building regex patterns (contain RegExp, new RegExp, or regex slashes)
		if (/\bRegExp\b|new\s+RegExp|\/.*\\b/.test(trimmed)) continue;
		// Skip lines that are string literals defining patterns
		if (/["'`].*\\b.*["'`]/.test(trimmed)) continue;

		if (asAnyPattern.test(trimmed)) {
			diagnostics.push(
				slop(
					relativePath,
					i + 1,
					"ai-slop/unsafe-type-assertion",
					"warning",
					`'${"as" + " any"}' bypasses type safety`,
					"Use a proper type or a more specific assertion",
					false,
				),
			);
		}

		if (doubleAssertPattern.test(trimmed)) {
			const isOrmReturn =
				/\.query[(<]/.test(trimmed) || /result\[0\]/.test(trimmed) || /rows\s/.test(trimmed);
			if (!isOrmReturn) {
				diagnostics.push(
					slop(
						relativePath,
						i + 1,
						"ai-slop/double-type-assertion",
						"warning",
						`Double type assertion (${"as" + " unknown as"} X) bypasses type checking`,
						"Refactor to avoid needing a double assertion. If this is an ORM query return, consider a typed wrapper function",
						false,
					),
				);
			}
		}
	}

	return diagnostics;
};

export const detectDeadPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const ext = path.extname(filePath);
		const relativePath = path.relative(context.rootDirectory, filePath);

		diagnostics.push(...detectConsoleLeftovers(content, relativePath, ext));
		diagnostics.push(...detectTodoStubs(content, relativePath));
		diagnostics.push(...detectDeadCodePatterns(content, relativePath, ext));
		diagnostics.push(...detectUnsafeTypePatterns(content, relativePath, ext));
	}

	return diagnostics;
};
