import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

// Top-level ES module imports only — side-effect / require / dynamic-import legitimately repeat and are excluded.
const IMPORT_FROM_RE = /^\s*import\s+[^;]*?from\s+["']([^"']+)["']/;

interface ImportLine {
	spec: string;
	line: number;
}

const extractImportLines = (content: string): ImportLine[] => {
	const lines = content.split("\n");
	const results: ImportLine[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const match = IMPORT_FROM_RE.exec(line);
		if (!match) continue;
		results.push({ spec: match[1], line: i + 1 });
	}
	return results;
};

export const detectDuplicateImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!JS_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const imports = extractImportLines(content);
		if (imports.length < 2) continue;

		const bySpec = new Map<string, ImportLine[]>();
		for (const imp of imports) {
			const list = bySpec.get(imp.spec) ?? [];
			list.push(imp);
			bySpec.set(imp.spec, list);
		}

		const relPath = path.relative(context.rootDirectory, filePath);
		for (const [spec, occurrences] of bySpec) {
			if (occurrences.length < 2) continue;
			// Flag the second-and-later occurrences; the first one is the canonical home.
			for (const dup of occurrences.slice(1)) {
				const firstLine = occurrences[0].line;
				diagnostics.push({
					filePath: relPath,
					engine: "ai-slop",
					rule: "ai-slop/duplicate-import",
					severity: "warning",
					message: `"${spec}" is also imported on line ${firstLine}. Merge into a single import statement.`,
					help: "Two imports from the same module split readers' attention and grow the import block. Run aislop fix to merge them automatically.",
					line: dup.line,
					column: 1,
					category: "AI Slop",
					fixable: true,
				});
			}
		}
	}

	return diagnostics;
};
