import fs from "node:fs";
import { isBuiltin } from "node:module";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { collectTsPathAliases, type AliasMatcher } from "./js-import-aliases.js";
import { collectWorkspaceDirs } from "./js-workspaces.js";
import { PYTHON_IMPORT_TO_PIP, PYTHON_STDLIB } from "./python-data.js";
import { collectPythonDeps } from "./python-manifest.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PY_EXTENSIONS = new Set([".py"]);

interface PackageManifest {
	jsDeps: Set<string>;
	pyDeps: Set<string>;
	hasJsManifest: boolean;
	hasPyManifest: boolean;
}

const readJson = (filePath: string): unknown => {
	try {
		return JSON.parse(fs.readFileSync(filePath, "utf-8"));
	} catch {
		return null;
	}
};

const PKG_DEP_SECTIONS = [
	"dependencies",
	"devDependencies",
	"peerDependencies",
	"optionalDependencies",
];

const addDepsFromPkg = (pkg: Record<string, unknown>, jsDeps: Set<string>): void => {
	for (const section of PKG_DEP_SECTIONS) {
		const deps = pkg[section];
		if (deps && typeof deps === "object") {
			for (const name of Object.keys(deps as Record<string, unknown>)) {
				jsDeps.add(name);
			}
		}
	}
};

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "out", "target", "coverage"]);
const NESTED_PKG_JSON_DEPTH = 4;

const collectNestedManifests = (rootDir: string, jsDeps: Set<string>): void => {
	const walk = (dir: string, depth: number): void => {
		if (depth > NESTED_PKG_JSON_DEPTH) return;
		let entries: import("node:fs").Dirent[];
		try {
			entries = fs.readdirSync(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (entry.name.startsWith(".") && entry.name !== ".github") continue;
			if (SKIP_DIRS.has(entry.name)) continue;
			const full = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				walk(full, depth + 1);
			} else if (entry.name === "package.json" && depth > 0) {
				const wsPkg = readJson(full) as Record<string, unknown> | null;
				if (!wsPkg) continue;
				if (typeof wsPkg.name === "string") jsDeps.add(wsPkg.name);
				addDepsFromPkg(wsPkg, jsDeps);
			}
		}
	};
	walk(rootDir, 0);
};

const collectJsDeps = (rootDir: string, jsDeps: Set<string>): boolean => {
	const pkgPath = path.join(rootDir, "package.json");
	if (!fs.existsSync(pkgPath)) return false;
	const pkg = readJson(pkgPath) as Record<string, unknown> | null;
	if (!pkg || typeof pkg !== "object") return false;
	addDepsFromPkg(pkg, jsDeps);
	if (typeof pkg.name === "string") jsDeps.add(pkg.name);

	const workspaceDirs = collectWorkspaceDirs(rootDir, pkg);
	for (const wsDir of workspaceDirs) {
		const wsPkg = readJson(path.join(wsDir, "package.json")) as Record<string, unknown> | null;
		if (!wsPkg) continue;
		if (typeof wsPkg.name === "string") jsDeps.add(wsPkg.name);
		addDepsFromPkg(wsPkg, jsDeps);
	}
	collectNestedManifests(rootDir, jsDeps);
	return true;
};

const loadManifest = (rootDir: string): PackageManifest => {
	const jsDeps = new Set<string>();
	const hasJsManifest = collectJsDeps(rootDir, jsDeps);
	const { pyDeps, hasPyManifest } = collectPythonDeps(rootDir);
	return { jsDeps, pyDeps, hasJsManifest, hasPyManifest };
};

const isJsRelativeOrAbsolute = (spec: string): boolean =>
	spec.startsWith(".") || spec.startsWith("/") || spec.startsWith("~/");

const RUNTIME_BUILTINS = new Set(["bun"]);
const isJsBuiltin = (spec: string): boolean => {
	if (RUNTIME_BUILTINS.has(spec)) return true;
	const stripped = spec.startsWith("node:") ? spec.slice(5) : spec;
	return isBuiltin(stripped) || isBuiltin(spec);
};

const VIRTUAL_MODULE_PREFIXES = ["astro:", "virtual:", "bun:", "file:"];
const isJsVirtualModule = (spec: string, manifest: PackageManifest): boolean => {
	if (VIRTUAL_MODULE_PREFIXES.some((p) => spec.startsWith(p))) return true;
	if (spec === "bun") return true;
	if (spec === "unfonts.css" && manifest.jsDeps.has("unplugin-fonts")) return true;
	if (spec.startsWith("~icons/") && manifest.jsDeps.has("unplugin-icons")) return true;
	return false;
};

const stripImportQuery = (spec: string): string => {
	const idx = spec.indexOf("?");
	return idx === -1 ? spec : spec.slice(0, idx);
};

// Filter out import-shaped substrings inside template literals or error messages — these chars never appear in real package names.
const TEMPLATE_PLACEHOLDER_RE = /\$\{/;
const isLikelyRealImportSpec = (spec: string): boolean => {
	if (spec.length === 0) return false;
	if (TEMPLATE_PLACEHOLDER_RE.test(spec)) return false;
	if (spec.includes("\\")) return false;
	if (/\s/.test(spec)) return false;
	return true;
};

const packageNameFromImport = (spec: string): string => {
	if (spec.startsWith("@")) {
		const parts = spec.split("/");
		return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : spec;
	}
	return spec.split("/")[0];
};

// The @types/* package providing types for a runtime package: `foo` -> `@types/foo`,
// `@scope/pkg` -> `@types/scope__pkg` (DefinitelyTyped scoped-name convention).
const typesPackageName = (pkg: string): string => {
	if (pkg.startsWith("@types/")) return pkg;
	if (pkg.startsWith("@")) return `@types/${pkg.slice(1).replace("/", "__")}`;
	return `@types/${pkg}`;
};

// Static `import ... from "spec"` anchored to start-of-line so it never matches
// `import { ... } from "x"` written *inside* a string literal in source.
const STATIC_IMPORT_RE = /^\s*import\s+(?:[\w*{},\s]+\s+from\s+)?["']([^"']+)["']/;
// Dynamic `import("spec")` and `require("spec")` can appear mid-line by design.
const DYNAMIC_IMPORT_RE = /(?:import|require)\s*\(\s*["']([^"']+)["']/g;

const extractJsImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		const staticMatch = STATIC_IMPORT_RE.exec(line);
		if (staticMatch && isLikelyRealImportSpec(staticMatch[1])) {
			results.push({ spec: staticMatch[1], line: i + 1 });
		}

		DYNAMIC_IMPORT_RE.lastIndex = 0;
		let dyn: RegExpExecArray | null = DYNAMIC_IMPORT_RE.exec(line);
		while (dyn !== null) {
			if (isLikelyRealImportSpec(dyn[1])) {
				results.push({ spec: dyn[1], line: i + 1 });
			}
			dyn = DYNAMIC_IMPORT_RE.exec(line);
		}
	}
	return results;
};

const extractPyImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i].trim();
		if (line.startsWith("#")) continue;
		// from X import ... — skip relative imports starting with .
		const fromMatch = line.match(/^from\s+([\w.]+)\s+import\b/);
		if (fromMatch && !fromMatch[1].startsWith(".")) {
			results.push({ spec: fromMatch[1], line: i + 1 });
			continue;
		}
		// import X[, Y as Z, ...]
		const importMatch = line.match(/^import\s+([\w.,\s]+?)(?:\s+as\s+\w+)?\s*$/);
		if (importMatch) {
			for (const raw of importMatch[1].split(",")) {
				const cleaned = raw.trim().split(/\s+as\s+/)[0];
				if (cleaned && !cleaned.startsWith(".")) {
					results.push({ spec: cleaned, line: i + 1 });
				}
			}
		}
	}
	return results;
};

const checkJsImport = (
	rawSpec: string,
	manifest: PackageManifest,
	tsAliasMatchers: AliasMatcher[],
): string | null => {
	const spec = stripImportQuery(rawSpec);
	if (spec.length === 0) return null;
	if (isJsRelativeOrAbsolute(spec)) return null;
	if (isJsBuiltin(spec)) return null;
	if (isJsVirtualModule(spec, manifest)) return null;
	if (tsAliasMatchers.some((m) => m(spec))) return null;
	const pkg = packageNameFromImport(spec);
	if (manifest.jsDeps.has(pkg)) return null;
	// Allow @types/X if X itself is in deps (the runtime impl) — common pattern.
	if (pkg.startsWith("@types/")) {
		const realPkg = pkg.slice("@types/".length);
		if (manifest.jsDeps.has(realPkg)) return null;
	}
	// Type-only imports backed by a declared @types/* package are not hallucinated.
	if (manifest.jsDeps.has(typesPackageName(pkg))) return null;
	return pkg;
};

const normalizePyName = (name: string): string => name.toLowerCase().replace(/_/g, "-");

const checkPyImport = (spec: string, manifest: PackageManifest): string | null => {
	const root = spec.split(".")[0];
	if (PYTHON_STDLIB.has(root)) return null;
	const normalized = normalizePyName(root);
	if (manifest.pyDeps.has(normalized)) return null;
	const distributions = PYTHON_IMPORT_TO_PIP[root] ?? PYTHON_IMPORT_TO_PIP[normalized];
	if (distributions?.some((dist) => manifest.pyDeps.has(normalizePyName(dist)))) return null;
	return root;
};

export const detectHallucinatedImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const rootPkg = readJson(path.join(context.rootDirectory, "package.json"));
	const workspaceDirs = collectWorkspaceDirs(context.rootDirectory, rootPkg);
	const manifest = loadManifest(context.rootDirectory);
	if (!manifest.hasJsManifest && !manifest.hasPyManifest) return [];
	const tsAliasMatchers = manifest.hasJsManifest
		? collectTsPathAliases(context.rootDirectory, workspaceDirs)
		: [];

	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		const ext = path.extname(filePath);
		const isJs = JS_EXTENSIONS.has(ext);
		const isPy = PY_EXTENSIONS.has(ext);
		if (!isJs && !isPy) continue;
		if (isJs && !manifest.hasJsManifest) continue;
		if (isPy && !manifest.hasPyManifest) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relPath = path.relative(context.rootDirectory, filePath);

		const imports = isJs ? extractJsImports(content) : extractPyImports(content);
		for (const { spec, line } of imports) {
			const hallucinated = isJs
				? checkJsImport(spec, manifest, tsAliasMatchers)
				: checkPyImport(spec, manifest);
			if (!hallucinated) continue;
			const manifestLabel = isJs ? "package.json" : "requirements.txt / pyproject.toml / Pipfile";
			diagnostics.push({
				filePath: relPath,
				engine: "ai-slop",
				rule: "ai-slop/hallucinated-import",
				severity: "error",
				message: `Imports "${hallucinated}" but it's not declared in ${manifestLabel}${isPy ? " and isn't Python stdlib" : ""}`,
				help: "Most often this is an LLM hallucinating a plausible-sounding package name. Either add the package to your manifest, or correct the import.",
				line,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};
