import fs from "node:fs";
import { isBuiltin } from "node:module";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { PYTHON_IMPORT_TO_PIP, PYTHON_STDLIB } from "./python-data.js";
import { collectPythonDeps } from "./python-manifest.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PY_EXTENSIONS = new Set([".py"]);

interface PackageManifest {
	jsDeps: Set<string>;
	pyDeps: Set<string>;
	hasJsManifest: boolean;
	hasPyManifest: boolean;
}

const readJson = (filePath: string): unknown => {
	try {
		return JSON.parse(fs.readFileSync(filePath, "utf-8"));
	} catch {
		return null;
	}
};

const PKG_DEP_SECTIONS = [
	"dependencies",
	"devDependencies",
	"peerDependencies",
	"optionalDependencies",
];

const addDepsFromPkg = (pkg: Record<string, unknown>, jsDeps: Set<string>): void => {
	for (const section of PKG_DEP_SECTIONS) {
		const deps = pkg[section];
		if (deps && typeof deps === "object") {
			for (const name of Object.keys(deps as Record<string, unknown>)) {
				jsDeps.add(name);
			}
		}
	}
};

const readWorkspaceGlobs = (rootDir: string, rootPkg: unknown): string[] => {
	const globs: string[] = [];
	if (rootPkg && typeof rootPkg === "object") {
		const ws = (rootPkg as Record<string, unknown>).workspaces;
		if (Array.isArray(ws)) {
			for (const g of ws) if (typeof g === "string") globs.push(g);
		} else if (ws && typeof ws === "object") {
			const pkgs = (ws as Record<string, unknown>).packages;
			if (Array.isArray(pkgs)) {
				for (const g of pkgs) if (typeof g === "string") globs.push(g);
			}
		}
	}
	const lerna = readJson(path.join(rootDir, "lerna.json")) as Record<string, unknown> | null;
	if (lerna && Array.isArray(lerna.packages)) {
		for (const g of lerna.packages) if (typeof g === "string") globs.push(g);
	}
	try {
		const pnpmWs = fs.readFileSync(path.join(rootDir, "pnpm-workspace.yaml"), "utf-8");
		let inPackages = false;
		for (const rawLine of pnpmWs.split("\n")) {
			if (/^packages\s*:\s*$/.test(rawLine)) {
				inPackages = true;
				continue;
			}
			if (!inPackages) continue;
			if (/^\S/.test(rawLine)) break;
			const m = rawLine.match(/^\s*-\s*["']?([^"'\n]+?)["']?\s*$/);
			if (m) globs.push(m[1].trim());
		}
	} catch {
		// no pnpm-workspace.yaml
	}
	return globs;
};

const expandWorkspaceDirs = (rootDir: string, globs: string[]): string[] => {
	const dirs: string[] = [];
	for (const glob of globs) {
		if (glob.endsWith("/*")) {
			const parent = path.join(rootDir, glob.slice(0, -2));
			try {
				for (const entry of fs.readdirSync(parent, { withFileTypes: true })) {
					if (entry.isDirectory()) dirs.push(path.join(parent, entry.name));
				}
			} catch {
				continue;
			}
		} else if (!glob.includes("*")) {
			dirs.push(path.join(rootDir, glob));
		}
	}
	return dirs;
};

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "out", "target", "coverage"]);
const NESTED_PKG_JSON_DEPTH = 4;

const collectNestedManifests = (rootDir: string, jsDeps: Set<string>): void => {
	const walk = (dir: string, depth: number): void => {
		if (depth > NESTED_PKG_JSON_DEPTH) return;
		let entries: import("node:fs").Dirent[];
		try {
			entries = fs.readdirSync(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (entry.name.startsWith(".") && entry.name !== ".github") continue;
			if (SKIP_DIRS.has(entry.name)) continue;
			const full = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				walk(full, depth + 1);
			} else if (entry.name === "package.json" && depth > 0) {
				const wsPkg = readJson(full) as Record<string, unknown> | null;
				if (!wsPkg) continue;
				if (typeof wsPkg.name === "string") jsDeps.add(wsPkg.name);
				addDepsFromPkg(wsPkg, jsDeps);
			}
		}
	};
	walk(rootDir, 0);
};

const collectJsDeps = (rootDir: string, jsDeps: Set<string>): boolean => {
	const pkgPath = path.join(rootDir, "package.json");
	if (!fs.existsSync(pkgPath)) return false;
	const pkg = readJson(pkgPath) as Record<string, unknown> | null;
	if (!pkg || typeof pkg !== "object") return false;
	addDepsFromPkg(pkg, jsDeps);
	if (typeof pkg.name === "string") jsDeps.add(pkg.name);

	const workspaceDirs = expandWorkspaceDirs(rootDir, readWorkspaceGlobs(rootDir, pkg));
	for (const wsDir of workspaceDirs) {
		const wsPkg = readJson(path.join(wsDir, "package.json")) as Record<string, unknown> | null;
		if (!wsPkg) continue;
		if (typeof wsPkg.name === "string") jsDeps.add(wsPkg.name);
		addDepsFromPkg(wsPkg, jsDeps);
	}
	collectNestedManifests(rootDir, jsDeps);
	return true;
};

type AliasMatcher = (spec: string) => boolean;

const TS_CONFIG_FILES = ["tsconfig.json", "jsconfig.json"];

const buildAliasMatcher = (key: string): AliasMatcher => {
	const starIdx = key.indexOf("*");
	if (starIdx === -1) {
		return (spec) => spec === key;
	}
	const before = key.slice(0, starIdx);
	const after = key.slice(starIdx + 1);
	return (spec) =>
		spec.length >= before.length + after.length && spec.startsWith(before) && spec.endsWith(after);
};

const collectAliasMatchersFromConfig = (configPath: string, matchers: AliasMatcher[]): void => {
	const config = readJson(configPath) as Record<string, unknown> | null;
	const opts = config?.compilerOptions as Record<string, unknown> | undefined;
	if (!opts) return;
	const paths = opts.paths;
	if (paths && typeof paths === "object") {
		for (const key of Object.keys(paths as Record<string, unknown>)) {
			matchers.push(buildAliasMatcher(key));
		}
	}
	const baseUrl = opts.baseUrl;
	if (typeof baseUrl === "string") {
		const baseUrlDir = path.resolve(path.dirname(configPath), baseUrl);
		let entries: string[];
		try {
			entries = fs.readdirSync(baseUrlDir);
		} catch {
			return;
		}
		const baseSpecifiers = new Set<string>();
		for (const entry of entries) {
			if (entry.startsWith(".") || entry === "node_modules") continue;
			const base = entry.replace(/\.(?:[jt]sx?|mjs|cjs|d\.ts)$/i, "");
			if (base.length > 0) baseSpecifiers.add(base);
		}
		for (const name of baseSpecifiers) {
			matchers.push((spec) => spec === name || spec.startsWith(`${name}/`));
		}
	}
};

const collectTsPathAliases = (rootDir: string): AliasMatcher[] => {
	const matchers: AliasMatcher[] = [];
	const rootPkg = readJson(path.join(rootDir, "package.json"));
	const dirs = [rootDir, ...expandWorkspaceDirs(rootDir, readWorkspaceGlobs(rootDir, rootPkg))];
	for (const dir of dirs) {
		for (const fname of TS_CONFIG_FILES) {
			collectAliasMatchersFromConfig(path.join(dir, fname), matchers);
		}
	}
	return matchers;
};

const loadManifest = (rootDir: string): PackageManifest => {
	const jsDeps = new Set<string>();
	const hasJsManifest = collectJsDeps(rootDir, jsDeps);
	const { pyDeps, hasPyManifest } = collectPythonDeps(rootDir);
	return { jsDeps, pyDeps, hasJsManifest, hasPyManifest };
};

const isJsRelativeOrAbsolute = (spec: string): boolean =>
	spec.startsWith(".") || spec.startsWith("/") || spec.startsWith("~/");

const RUNTIME_BUILTINS = new Set(["bun"]);
const isJsBuiltin = (spec: string): boolean => {
	if (RUNTIME_BUILTINS.has(spec)) return true;
	const stripped = spec.startsWith("node:") ? spec.slice(5) : spec;
	return isBuiltin(stripped) || isBuiltin(spec);
};

const VIRTUAL_MODULE_PREFIXES = ["astro:", "virtual:", "bun:", "~icons/"];
const isJsVirtualModule = (spec: string): boolean =>
	VIRTUAL_MODULE_PREFIXES.some((p) => spec.startsWith(p));

const stripImportQuery = (spec: string): string => {
	const idx = spec.indexOf("?");
	return idx === -1 ? spec : spec.slice(0, idx);
};

const VIRTUAL_ASSET_FILES: Record<string, string> = {
	"unfonts.css": "unplugin-fonts",
};

// Filter out import-shaped substrings inside template literals or error messages — these chars never appear in real package names.
const TEMPLATE_PLACEHOLDER_RE = /\$\{/;
const isLikelyRealImportSpec = (spec: string): boolean => {
	if (spec.length === 0) return false;
	if (TEMPLATE_PLACEHOLDER_RE.test(spec)) return false;
	if (spec.includes("\\")) return false;
	if (/\s/.test(spec)) return false;
	return true;
};

const packageNameFromImport = (spec: string): string => {
	if (spec.startsWith("@")) {
		const parts = spec.split("/");
		return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : spec;
	}
	return spec.split("/")[0];
};

// Static `import ... from "spec"` anchored to start-of-line so it never matches
// `import { ... } from "x"` written *inside* a string literal in source.
const STATIC_IMPORT_RE = /^\s*import\s+(?:[\w*{},\s]+\s+from\s+)?["']([^"']+)["']/;
// Dynamic `import("spec")` and `require("spec")` can appear mid-line by design.
const DYNAMIC_IMPORT_RE = /(?:import|require)\s*\(\s*["']([^"']+)["']/g;

const extractJsImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		const staticMatch = STATIC_IMPORT_RE.exec(line);
		if (staticMatch && isLikelyRealImportSpec(staticMatch[1])) {
			results.push({ spec: staticMatch[1], line: i + 1 });
		}

		DYNAMIC_IMPORT_RE.lastIndex = 0;
		let dyn: RegExpExecArray | null = DYNAMIC_IMPORT_RE.exec(line);
		while (dyn !== null) {
			if (isLikelyRealImportSpec(dyn[1])) {
				results.push({ spec: dyn[1], line: i + 1 });
			}
			dyn = DYNAMIC_IMPORT_RE.exec(line);
		}
	}
	return results;
};

const extractPyImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i].trim();
		if (line.startsWith("#")) continue;
		// from X import ... — skip relative imports starting with .
		const fromMatch = line.match(/^from\s+([\w.]+)\s+import\b/);
		if (fromMatch && !fromMatch[1].startsWith(".")) {
			results.push({ spec: fromMatch[1], line: i + 1 });
			continue;
		}
		// import X[, Y as Z, ...]
		const importMatch = line.match(/^import\s+([\w.,\s]+?)(?:\s+as\s+\w+)?\s*$/);
		if (importMatch) {
			for (const raw of importMatch[1].split(",")) {
				const cleaned = raw.trim().split(/\s+as\s+/)[0];
				if (cleaned && !cleaned.startsWith(".")) {
					results.push({ spec: cleaned, line: i + 1 });
				}
			}
		}
	}
	return results;
};

const checkJsImport = (
	rawSpec: string,
	manifest: PackageManifest,
	tsAliasMatchers: AliasMatcher[],
): string | null => {
	const spec = stripImportQuery(rawSpec);
	if (spec.length === 0) return null;
	if (isJsRelativeOrAbsolute(spec)) return null;
	if (isJsBuiltin(spec)) return null;
	if (isJsVirtualModule(spec)) return null;
	const virtualOwner = VIRTUAL_ASSET_FILES[spec];
	if (virtualOwner && manifest.jsDeps.has(virtualOwner)) return null;
	if (tsAliasMatchers.some((m) => m(spec))) return null;
	const pkg = packageNameFromImport(spec);
	if (manifest.jsDeps.has(pkg)) return null;
	// Allow @types/X if X itself is in deps (the runtime impl) — common pattern.
	if (pkg.startsWith("@types/")) {
		const realPkg = pkg.slice("@types/".length);
		if (manifest.jsDeps.has(realPkg)) return null;
	}
	return pkg;
};

const checkPyImport = (spec: string, manifest: PackageManifest): string | null => {
	const root = spec.split(".")[0];
	if (PYTHON_STDLIB.has(root)) return null;
	const normalized = root.toLowerCase().replace(/_/g, "-");
	if (manifest.pyDeps.has(normalized)) return null;
	const pipName = PYTHON_IMPORT_TO_PIP[root];
	if (pipName && manifest.pyDeps.has(pipName)) return null;
	return root;
};

export const detectHallucinatedImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const manifest = loadManifest(context.rootDirectory);
	if (!manifest.hasJsManifest && !manifest.hasPyManifest) return [];
	const tsAliasMatchers = manifest.hasJsManifest ? collectTsPathAliases(context.rootDirectory) : [];

	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		const ext = path.extname(filePath);
		const isJs = JS_EXTENSIONS.has(ext);
		const isPy = PY_EXTENSIONS.has(ext);
		if (!isJs && !isPy) continue;
		if (isJs && !manifest.hasJsManifest) continue;
		if (isPy && !manifest.hasPyManifest) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relPath = path.relative(context.rootDirectory, filePath);

		const imports = isJs ? extractJsImports(content) : extractPyImports(content);
		for (const { spec, line } of imports) {
			const hallucinated = isJs
				? checkJsImport(spec, manifest, tsAliasMatchers)
				: checkPyImport(spec, manifest);
			if (!hallucinated) continue;
			const manifestLabel = isJs ? "package.json" : "requirements.txt / pyproject.toml / Pipfile";
			diagnostics.push({
				filePath: relPath,
				engine: "ai-slop",
				rule: "ai-slop/hallucinated-import",
				severity: "error",
				message: `Imports "${hallucinated}" but it's not declared in ${manifestLabel}${isPy ? " and isn't Python stdlib" : ""}`,
				help: "Most often this is an LLM hallucinating a plausible-sounding package name. Either add the package to your manifest, or correct the import.",
				line,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};
