import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const SOURCE_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".mjs",
	".cjs",
	".py",
	".go",
	".rs",
	".rb",
	".java",
	".php",
]);

const URL_LITERAL_RE = /(["'`])(https?:\/\/[^"'`\s<>]+)\1/g;
const ID_LITERAL_RE = /(["'])([A-Za-z][A-Za-z0-9_-]{15,})\1/g;
const ENV_REFERENCE_RE =
	/\b(?:process\.env|import\.meta\.env|Deno\.env|os\.environ|getenv|env\()\b/i;
const DOC_URL_CONTEXT_RE =
	/\b(?:docs?|documentation|homepage|repository|bugs|license|readme|source|svgUrl|pageUrl|href|link|install)\b/i;
const URL_CONFIG_CONTEXT_RE =
	/\b(?:api|base[_-]?url|baseUrl|endpoint|host|origin|webhook|callback|redirect|server|service|domain|url)\b/i;
const ENVIRONMENT_HOST_RE =
	/(?:^|[.-])(?:api|app|admin|auth|staging|stage|prod|dev|sandbox|webhook|internal)(?:[.-]|$)|^(?:localhost|127\.0\.0\.1|0\.0\.0\.0)$/i;
const ID_CONTEXT_RE =
	/(?:^|[^A-Za-z0-9])(?:api[_-]?key|client[_-]?id|project[_-]?id|org(?:anization)?[_-]?id|workspace[_-]?id|tenant[_-]?id|price[_-]?id|product[_-]?id|customer[_-]?id|subscription[_-]?id|account[_-]?id|app[_-]?id|key|token|secret)(?:$|[^A-Za-z0-9])/i;
const MIGRATION_PATH_RE = /(?:^|[\\/])(?:migrations?|db[\\/]migrate)[\\/]/i;
const PLACEHOLDER_HOSTS = new Set(["example.com", "example.org", "example.net"]);
const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "0.0.0.0", "::1"]);
const PLACEHOLDER_ID_RE = /^(?:changeme|replace[_-]?me|your[_-]|example|placeholder|todo)/i;

interface FindingSpec {
	rule: string;
	message: string;
	help: string;
}

const HARDCODED_URL_FINDING: FindingSpec = {
	rule: "ai-slop/hardcoded-url",
	message: "Hardcoded environment URL in production code",
	help: "Move deployment-specific URLs to environment variables or a typed config module. Keep only stable documentation/public links inline.",
};

const HARDCODED_ID_FINDING: FindingSpec = {
	rule: "ai-slop/hardcoded-id",
	message: "Hardcoded provider/project ID in production code",
	help: "Move provider IDs, tenant IDs, price IDs, and similar deployment-specific identifiers to env/config so agents do not bake one environment into source.",
};

const makeFinding = (filePath: string, line: number, spec: FindingSpec): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule: spec.rule,
	severity: "warning",
	message: spec.message,
	help: spec.help,
	line,
	column: 0,
	category: "AI Slop",
	fixable: false,
});

const isCommentOnlyLine = (trimmed: string): boolean =>
	trimmed.startsWith("//") ||
	trimmed.startsWith("#") ||
	trimmed.startsWith("*") ||
	trimmed.startsWith("/*");

const commentStartsBefore = (line: string, index: number, ext: string): boolean => {
	const prefix = line.slice(0, index);
	if (ext === ".py" || ext === ".rb") return prefix.includes("#");
	if (ext === ".php") return prefix.includes("//") || prefix.includes("#");
	return prefix.includes("//") || prefix.includes("/*");
};

const safeUrlHost = (urlText: string): string | null => {
	try {
		return new URL(urlText).hostname.toLowerCase();
	} catch {
		return null;
	}
};

const isEnvBackedLine = (line: string): boolean => ENV_REFERENCE_RE.test(line);

const shouldFlagUrlLiteral = (line: string, urlText: string): boolean => {
	if (isEnvBackedLine(line)) return false;
	const host = safeUrlHost(urlText);
	if (!host) return false;
	if (PLACEHOLDER_HOSTS.has(host)) return false;
	if (LOOPBACK_HOSTS.has(host)) return false;
	if (DOC_URL_CONTEXT_RE.test(line) && !ENVIRONMENT_HOST_RE.test(host)) return false;
	return URL_CONFIG_CONTEXT_RE.test(line) || ENVIRONMENT_HOST_RE.test(host);
};

const ENV_VAR_NAME_RE = /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/;

const hasUsefulIdShape = (value: string): boolean => {
	if (PLACEHOLDER_ID_RE.test(value)) return false;
	if (ENV_VAR_NAME_RE.test(value)) return false;
	if (/^https?:\/\//i.test(value)) return false;
	if (/^[A-Za-z]+$/.test(value)) return false;
	// A digit separates an opaque ID from a readable slug/storage key.
	return /[0-9]/.test(value);
};

const scanLineForConfigLiterals = (
	line: string,
	relativePath: string,
	ext: string,
	lineNumber: number,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const trimmed = line.trim();
	if (isCommentOnlyLine(trimmed)) return diagnostics;

	URL_LITERAL_RE.lastIndex = 0;
	let urlMatch: RegExpExecArray | null;
	while ((urlMatch = URL_LITERAL_RE.exec(line)) !== null) {
		const urlText = urlMatch[2];
		if (commentStartsBefore(line, urlMatch.index, ext)) continue;
		if (!shouldFlagUrlLiteral(line, urlText)) continue;
		diagnostics.push(makeFinding(relativePath, lineNumber, HARDCODED_URL_FINDING));
	}

	if (!ID_CONTEXT_RE.test(line) || isEnvBackedLine(line) || DOC_URL_CONTEXT_RE.test(line)) {
		return diagnostics;
	}

	ID_LITERAL_RE.lastIndex = 0;
	let idMatch: RegExpExecArray | null;
	while ((idMatch = ID_LITERAL_RE.exec(line)) !== null) {
		const value = idMatch[2];
		if (commentStartsBefore(line, idMatch.index, ext)) continue;
		if (!hasUsefulIdShape(value)) continue;
		diagnostics.push(makeFinding(relativePath, lineNumber, HARDCODED_ID_FINDING));
	}

	return diagnostics;
};

const scanFileForConfigLiterals = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	if (!SOURCE_EXTENSIONS.has(ext)) return [];
	if (isNonProductionPath(relativePath)) return [];
	if (MIGRATION_PATH_RE.test(relativePath)) return [];

	return content
		.split("\n")
		.flatMap((line, index) => scanLineForConfigLiterals(line, relativePath, ext, index + 1));
};

export const detectHardcodedConfigLiterals = async (
	context: EngineContext,
): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];

	for (const filePath of getSourceFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relativePath = path.relative(context.rootDirectory, filePath);
		const ext = path.extname(filePath);
		diagnostics.push(...scanFileForConfigLiterals(content, relativePath, ext));
	}

	return diagnostics;
};
