import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import {
	CROSS_REFERENCE_PHRASES,
	DECL_START,
	DECORATIVE_SECTION_HEADER,
	DECORATIVE_SEPARATOR,
	EXPLANATORY_OPENERS,
	EXPLANATORY_WHY_MARKERS,
	EXPORT_DEFAULT,
	GO_DECL_START,
	JAVA_DECL_START,
	JAVA_DECL_START_FALLBACK,
	JUSTIFICATION_OPENERS,
	MEANINGFUL_JSDOC_TAGS,
	PHP_DECL_START,
	PY_DECL_START,
	RUBY_DECL_START,
	RUST_DECL_START,
	SECTION_HEADER,
	SUPPORTED_EXTS,
	TS_MEMBER_DECL_START,
} from "./narrative-comments-patterns.js";
import { isNonProductionPath } from "./non-production-paths.js";

type BlockKind = "line" | "jsdoc";

interface CommentBlock {
	kind: BlockKind;
	startLine: number;
	endLine: number;
	rawLines: string[];
	prose: string[];
	hasMeaningfulJsdocTag: boolean;
	isRustDoc: boolean;
	nextNonBlankLine: string | null;
}

const stripJsdocLine = (line: string): string =>
	line
		.replace(/^\s*\/\*\*+\s?/, "")
		.replace(/\s*\*+\/\s*$/, "")
		.replace(/^\s*\*\s?/, "")
		.trim();

const stripLineComment = (line: string): string => line.replace(/^\s*(?:(?:\/\/)|#)\s?/, "");

export const getCommentSyntax = (ext: string): { linePrefixes: string[] } | null => {
	switch (ext) {
		case ".ts":
		case ".tsx":
		case ".js":
		case ".jsx":
		case ".mjs":
		case ".cjs":
		case ".go":
		case ".rs":
		case ".java":
			return { linePrefixes: ["//"] };
		case ".py":
		case ".rb":
			return { linePrefixes: ["#"] };
		case ".php":
			return { linePrefixes: ["//", "#"] };
		default:
			return null;
	}
};

const getMatchedLinePrefix = (line: string, syntax: { linePrefixes: string[] }): string | null => {
	const trimmed = line.trimStart();
	for (const prefix of syntax.linePrefixes) {
		if (!trimmed.startsWith(prefix)) continue;
		if (prefix === "#" && trimmed.startsWith("#!")) return null;
		return prefix;
	}
	return null;
};

const isRustDocCommentLine = (line: string): boolean => {
	const trimmed = line.trimStart();
	return trimmed.startsWith("///") || trimmed.startsWith("//!");
};

export const collectBlocks = (
	sourceLines: string[],
	syntax: { linePrefixes: string[] },
): CommentBlock[] => {
	const blocks: CommentBlock[] = [];
	let i = 0;
	while (i < sourceLines.length) {
		const line = sourceLines[i];
		const trimmed = line.trim();
		const matchedPrefix = getMatchedLinePrefix(line, syntax);

		if (matchedPrefix !== null) {
			const start = i;
			const raw: string[] = [];
			while (i < sourceLines.length && getMatchedLinePrefix(sourceLines[i], syntax) !== null) {
				raw.push(sourceLines[i]);
				i += 1;
			}
			let next = i;
			while (next < sourceLines.length && sourceLines[next].trim() === "") next += 1;
			const docCandidates = raw.filter((l) => l.trim().length > 0);
			const isRustDoc =
				docCandidates.length > 0 && docCandidates.every((l) => isRustDocCommentLine(l));
			blocks.push({
				kind: "line",
				startLine: start + 1,
				endLine: start + raw.length,
				rawLines: raw,
				prose: raw.map(stripLineComment),
				hasMeaningfulJsdocTag: false,
				isRustDoc,
				nextNonBlankLine: next < sourceLines.length ? sourceLines[next] : null,
			});
			continue;
		}

		if (trimmed.startsWith("/**")) {
			const start = i;
			const raw: string[] = [sourceLines[i]];
			let hasClose = /\*\/\s*$/.test(sourceLines[i]) && sourceLines[i].trim() !== "/**";
			i += 1;
			while (!hasClose && i < sourceLines.length) {
				raw.push(sourceLines[i]);
				if (/\*\/\s*$/.test(sourceLines[i])) {
					hasClose = true;
				}
				i += 1;
			}
			let next = i;
			while (next < sourceLines.length && sourceLines[next].trim() === "") next += 1;

			const prose = raw.map(stripJsdocLine).filter((l) => l.length > 0 && !l.startsWith("@"));
			const tagNames: string[] = [];
			for (const line of raw) {
				const stripped = stripJsdocLine(line);
				if (stripped.startsWith("@")) {
					const tagMatch = stripped.match(/^@(\w+)/);
					if (tagMatch) tagNames.push(tagMatch[1].toLowerCase());
				}
			}
			const hasMeaningful = tagNames.some((t) => MEANINGFUL_JSDOC_TAGS.has(t));
			blocks.push({
				kind: "jsdoc",
				startLine: start + 1,
				endLine: start + raw.length,
				rawLines: raw,
				prose,
				hasMeaningfulJsdocTag: hasMeaningful,
				isRustDoc: false,
				nextNonBlankLine: next < sourceLines.length ? sourceLines[next] : null,
			});
			continue;
		}

		i += 1;
	}
	return blocks;
};

const looksLikeDeclarationPreamble = (nextLine: string | null, ext: string): boolean => {
	if (nextLine === null) return false;
	if (DECL_START.test(nextLine) || EXPORT_DEFAULT.test(nextLine)) return true;

	switch (ext) {
		case ".py":
			return PY_DECL_START.test(nextLine);
		case ".go":
			return GO_DECL_START.test(nextLine);
		case ".rs":
			return RUST_DECL_START.test(nextLine);
		case ".rb":
			return RUBY_DECL_START.test(nextLine);
		case ".java":
			return JAVA_DECL_START.test(nextLine) || JAVA_DECL_START_FALLBACK.test(nextLine);
		case ".php":
			return PHP_DECL_START.test(nextLine);
		case ".ts":
		case ".tsx":
		case ".js":
		case ".jsx":
		case ".mjs":
		case ".cjs":
			return TS_MEMBER_DECL_START.test(nextLine);
		default:
			return false;
	}
};

const looksLikeLicenseHeader = (block: CommentBlock): boolean => {
	if (block.startLine !== 1) return false;
	const text = block.rawLines.join(" ").toLowerCase();
	return (
		text.includes("copyright") ||
		text.includes("license") ||
		text.includes("spdx-license-identifier")
	);
};

const BARE_LABEL_RE = /^[A-Z][A-Za-z0-9 ]{1,28}$/;
const isBareSectionLabel = (prose: string): boolean => {
	if (!BARE_LABEL_RE.test(prose)) return false;
	if (prose.endsWith(".")) return false;
	const words = prose.split(/\s+/);
	if (words.length > 3) return false;
	return true;
};

const DATA_ENTRY_START = /^\s*(?:\{|\[|["'`]|\d|\w+:\s|case\s)/;
const nextLineLooksLikeDataEntry = (nextLine: string | null): boolean => {
	if (nextLine === null) return false;
	if (!DATA_ENTRY_START.test(nextLine)) return false;
	const trimmed = nextLine.trim();
	if (trimmed.startsWith("case ")) return true;
	if (
		trimmed.startsWith("{") ||
		trimmed.startsWith("[") ||
		trimmed.startsWith('"') ||
		trimmed.startsWith("'") ||
		trimmed.startsWith("`")
	)
		return true;
	if (/^\w+\s*:/.test(trimmed)) return true;
	return false;
};

const looksLikeSuppressDirective = (block: CommentBlock): boolean =>
	block.rawLines.some((l) =>
		/\b(biome-ignore|eslint-disable|ts-ignore|ts-expect-error|@ts-\w+|noqa|pylint:\s*disable|rubocop:disable|noinspection|phpcs:disable)\b/.test(
			l,
		),
	);

const GO_DECL_NAME_RE = /^(?:func|type|var|const)\s+(?:\([^)]*\)\s*)?(\w+)/;
const looksLikeGoDocComment = (block: CommentBlock, ext: string): boolean => {
	if (ext !== ".go" || block.kind !== "line") return false;
	const next = block.nextNonBlankLine;
	if (!next) return false;
	const declMatch = GO_DECL_NAME_RE.exec(next.trim());
	if (!declMatch) return false;
	const firstProse = block.prose.find((l) => l.length > 0) ?? "";
	const firstWord = firstProse.split(/\s+/)[0] ?? "";
	return firstWord === declMatch[1];
};

const DOC_INDICATOR_RE =
	/`[^`]+`|\|\s*[-:]+\s*\||```|\b(?:note|warning|warn|caveat|example|caution|see):|\(e\.g\.[^)]+\)|\(i\.e\.[^)]+\)/i;
const hasDocIndicator = (block: CommentBlock): boolean => {
	const joined = block.prose.join(" ");
	if (DOC_INDICATOR_RE.test(joined)) return true;
	for (const l of block.prose) {
		if (/^[-]\s/.test(l)) return true;
	}
	return false;
};

const hasPreambleSlopSignal = (block: CommentBlock): boolean => {
	const joined = block.prose.join(" ");
	for (const l of block.prose) {
		if (EXPLANATORY_OPENERS.test(l)) return true;
		if (JUSTIFICATION_OPENERS.some((re) => re.test(l))) return true;
	}
	return CROSS_REFERENCE_PHRASES.some((re) => re.test(joined));
};

const detectNarrativeInBlock = (
	block: CommentBlock,
	ext: string,
): { matched: boolean; reason: string } => {
	if (looksLikeLicenseHeader(block)) return { matched: false, reason: "" };
	if (looksLikeSuppressDirective(block)) return { matched: false, reason: "" };
	if (block.kind === "jsdoc" && block.hasMeaningfulJsdocTag) return { matched: false, reason: "" };
	if (block.isRustDoc) return { matched: false, reason: "" };
	if (looksLikeGoDocComment(block, ext)) return { matched: false, reason: "" };

	if (
		block.kind === "line" &&
		block.prose.some((l) => DECORATIVE_SEPARATOR.test(l) || DECORATIVE_SECTION_HEADER.test(l))
	) {
		return { matched: true, reason: "decorative separator" };
	}

	if (block.kind === "line" && block.prose.some((l) => SECTION_HEADER.test(l))) {
		return { matched: true, reason: "phase/section header" };
	}

	if (
		block.kind === "line" &&
		block.prose.length === 1 &&
		isBareSectionLabel(block.prose[0]) &&
		!nextLineLooksLikeDataEntry(block.nextNonBlankLine)
	) {
		return { matched: true, reason: "bare section label" };
	}

	const joined = block.prose.join(" ");
	const hasWhyMarker = EXPLANATORY_WHY_MARKERS.test(joined);

	if ((hasWhyMarker || hasDocIndicator(block)) && block.kind === "jsdoc") {
		return { matched: false, reason: "" };
	}

	if (
		block.kind === "line" &&
		block.prose.length >= 3 &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext)
	) {
		return { matched: true, reason: "multi-line preamble before declaration" };
	}

	if (
		block.kind === "jsdoc" &&
		block.prose.length >= 3 &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext) &&
		hasPreambleSlopSignal(block)
	) {
		return { matched: true, reason: "JSDoc preamble with slop signal" };
	}

	if (CROSS_REFERENCE_PHRASES.some((re) => re.test(joined))) {
		return { matched: true, reason: "cross-reference commentary" };
	}

	if (block.kind === "line") {
		for (const l of block.prose) {
			if (JUSTIFICATION_OPENERS.some((re) => re.test(l))) {
				return { matched: true, reason: "justification prose" };
			}
		}
	}

	if (
		block.kind === "line" &&
		block.rawLines.length === 1 &&
		EXPLANATORY_OPENERS.test(block.prose[0] ?? "") &&
		looksLikeDeclarationPreamble(block.nextNonBlankLine, ext)
	) {
		return { matched: true, reason: "explanatory preamble" };
	}

	const nonEmptyProseCount = block.prose.filter((l) => l.length > 0).length;

	if (nonEmptyProseCount >= 5) {
		return { matched: true, reason: "long narrative block" };
	}

	if (nonEmptyProseCount >= 3 && !hasWhyMarker && block.kind === "line") {
		return { matched: true, reason: "multi-line narrative prose" };
	}

	return { matched: false, reason: "" };
};

export const detectNarrativeComments = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const ext = path.extname(filePath);
		if (!SUPPORTED_EXTS.has(ext)) continue;
		if (isAutoGenerated(filePath)) continue;
		const syntax = getCommentSyntax(ext);
		if (!syntax) continue;

		const relativePath = path.relative(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const blocks = collectBlocks(lines, syntax);

		for (const block of blocks) {
			const { matched, reason } = detectNarrativeInBlock(block, ext);
			if (!matched) continue;

			diagnostics.push({
				filePath: relativePath,
				engine: "ai-slop",
				rule: "ai-slop/narrative-comment",
				severity: "warning",
				message: `Narrative comment block (${reason})`,
				help: "Remove — narrative/decorative comments belong in PR descriptions, not source. Code should be self-explanatory.",
				line: block.startLine,
				column: 0,
				category: "Comments",
				fixable: true,
			});
		}
	}

	return diagnostics;
};
