import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const PY_EXTENSIONS = new Set([".py"]);

const BARE_EXCEPT_RE = /^\s*except\s*:\s*(?:#.*)?$/;
const BROAD_EXCEPT_RE = /^\s*except\s+(Exception|BaseException)\s*(?:as\s+\w+)?\s*:\s*(?:#.*)?$/;
const PRINT_RE = /^\s*print\s*\(/;
const DEF_RE = /^\s*(?:async\s+)?def\s+\w+\s*\(/;
const MUTABLE_DEFAULT_RE = /(\w+)\s*(?::\s*[^,)=]+)?\s*=\s*(\[\s*\]|\{\s*\}|set\(\s*\))/;
const RANGE_LEN_LOOP_RE =
	/^\s*for\s+([A-Za-z_]\w*)\s+in\s+range\s*\(\s*len\s*\(\s*([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*\)\s*\)\s*:\s*(?:#.*)?$/;
const CHAINED_DICT_GET_RE = /\.get\s*\([^)]*,\s*\{\s*\}\s*\)\s*\.get\s*\(/;
const SAME_VALUE_BRANCH_RE =
	/^(\s*)(?:if|elif)\s+([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*==\s*["'][^"']+["']\s*:/;
const INSTANCE_BRANCH_RE = /^(\s*)(?:if|elif)\s+isinstance\s*\(\s*([A-Za-z_]\w*)\s*,\s*[^)]+\)\s*:/;
const BRANCH_LADDER_THRESHOLD = 4;

const isTestFile = (relPath: string, basename: string): boolean =>
	basename.startsWith("test_") ||
	basename.endsWith("_test.py") ||
	basename === "conftest.py" ||
	relPath.split(path.sep).some((seg) => seg === "tests" || seg === "test");

const isScriptOrEntrypoint = (basename: string): boolean =>
	basename === "__main__.py" || basename === "manage.py" || basename === "setup.py";

const SCRIPT_DIR_NAMES = new Set([
	"scripts",
	"bin",
	".github",
	"action",
	"docs",
	"docs_src",
	"examples",
	"example",
]);

const isInScriptDir = (relPath: string): boolean =>
	relPath.split(path.sep).some((seg) => SCRIPT_DIR_NAMES.has(seg));

// Documentation/tutorial files in Python projects use print() to demonstrate output.
const isTutorialFile = (basename: string): boolean =>
	basename.startsWith("tutorial") && basename.endsWith(".py");

const MAIN_GUARD_RE = /^\s*if\s+__name__\s*==\s*["']__main__["']\s*:/;
const hasMainGuard = (lines: string[]): boolean => lines.some((l) => MAIN_GUARD_RE.test(l));

const buildDocstringRanges = (lines: string[]): Set<number> => {
	const inside = new Set<number>();
	let openDelim: '"""' | "'''" | null = null;
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (openDelim) {
			inside.add(i);
			if (line.includes(openDelim)) openDelim = null;
			continue;
		}
		// Find an opening triple-quote that isn't closed on the same line.
		for (const delim of ['"""', "'''"] as const) {
			const first = line.indexOf(delim);
			if (first === -1) continue;
			const second = line.indexOf(delim, first + 3);
			if (second === -1) {
				openDelim = delim;
				inside.add(i);
				break;
			}
		}
	}
	return inside;
};

interface FlagArgs {
	relPath: string;
	rule: string;
	severity: "warning" | "error" | "info";
	message: string;
	help: string;
	line: number;
}

const pushFinding = (out: Diagnostic[], a: FlagArgs): void => {
	out.push({
		filePath: a.relPath,
		engine: "ai-slop",
		rule: a.rule,
		severity: a.severity,
		message: a.message,
		help: a.help,
		line: a.line,
		column: 1,
		category: "AI Slop",
		fixable: false,
	});
};

type FindingTemplate = Omit<FlagArgs, "relPath" | "line">;

const pushLineFinding = (
	out: Diagnostic[],
	relPath: string,
	line: number,
	finding: FindingTemplate,
): void => {
	pushFinding(out, { relPath, line, ...finding });
};

const flagBareExcept = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (!BARE_EXCEPT_RE.test(lines[i])) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-bare-except",
			severity: "warning",
			message:
				"Bare `except:` swallows every exception including KeyboardInterrupt and SystemExit.",
			help: "Catch the specific exception type you actually expect (`except ValueError:`, `except (KeyError, IndexError):`). If you genuinely want everything, `except BaseException:` plus a re-raise or log makes the intent explicit.",
			line: i + 1,
		});
	}
};

const flagBroadExceptWithSilentBody = (
	lines: string[],
	relPath: string,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const match = BROAD_EXCEPT_RE.exec(lines[i]);
		if (!match) continue;
		const next = lines[i + 1] ?? "";
		const trimmedNext = next.trim();
		// Quiet body == only `pass` or only a comment, with nothing else inside the suite.
		const isSilent =
			trimmedNext === "pass" ||
			(trimmedNext.startsWith("#") && (lines[i + 2] ?? "").trim() === "pass");
		if (!isSilent) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-broad-except",
			severity: "warning",
			message: `\`except ${match[1]}: pass\` silently drops every exception. Failures vanish without a trace.`,
			help: "Either narrow the exception class (`except ValueError:`), log the error, or re-raise. If you genuinely intend to swallow, add a comment naming the specific failure mode you're handling — auditors will thank you.",
			line: i + 1,
		});
	}
};

const flagMutableDefaults = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	let i = 0;
	while (i < lines.length) {
		if (!DEF_RE.test(lines[i])) {
			i++;
			continue;
		}
		// Walk forward until the signature closes (line ending with `:` after balanced parens).
		const startLine = i;
		let signature = lines[i];
		let parenDepth = 0;
		for (const ch of signature) {
			if (ch === "(") parenDepth++;
			else if (ch === ")") parenDepth--;
		}
		while (parenDepth > 0 && i + 1 < lines.length) {
			i++;
			signature += `\n${lines[i]}`;
			for (const ch of lines[i]) {
				if (ch === "(") parenDepth++;
				else if (ch === ")") parenDepth--;
			}
		}
		MUTABLE_DEFAULT_RE.lastIndex = 0;
		const found = MUTABLE_DEFAULT_RE.exec(signature);
		if (found) {
			pushFinding(out, {
				relPath,
				rule: "ai-slop/python-mutable-default",
				severity: "warning",
				message: `Mutable default argument \`${found[1]}=${found[2]}\`. The default is shared across all calls — bugs that look like state-leakage.`,
				help: "Use `None` as the default and create the mutable value inside the body: `def f(items=None): items = items if items is not None else []`. Standard Python idiom; anything else is the AI agent shortcutting.",
				line: startLine + 1,
			});
		}
		i++;
	}
};

const flagPrintInProduction = (
	lines: string[],
	relPath: string,
	basename: string,
	out: Diagnostic[],
): void => {
	if (isTestFile(relPath, basename) || isScriptOrEntrypoint(basename)) return;
	if (isInScriptDir(relPath)) return;
	if (isTutorialFile(basename)) return;
	// Files with a main-guard treat their print() calls as CLI output, not debug residue.
	if (hasMainGuard(lines)) return;
	const docstringLines = buildDocstringRanges(lines);
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (!PRINT_RE.test(line)) continue;
		const trimmed = line.trim();
		if (trimmed.startsWith("#")) continue;
		if (docstringLines.has(i)) continue;
		pushFinding(out, {
			relPath,
			rule: "ai-slop/python-print-debug",
			severity: "warning",
			message: "`print()` in production code — usually a leftover debug statement.",
			help: "Use the project's logger (`logging.getLogger(__name__).info(...)`). If this file is genuinely a CLI entry point (typer/click/argparse), it's safe to ignore — but rename to `__main__.py` or move under `scripts/` so the rule skips it next time.",
			line: i + 1,
		});
	}
};

const flagRangeLenLoops = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const match = RANGE_LEN_LOOP_RE.exec(lines[i]);
		if (!match) continue;
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-range-len-loop",
			severity: "info",
			message: `\`range(len(${match[2]}))\` loop — usually a hand-rolled iteration pattern.`,
			help: "Prefer direct iteration (`for item in items`) or `enumerate(items)` when the index is needed. Keeping index plumbing out of the loop reduces checkpoint-to-checkpoint bloat.",
		});
	}
};

const flagChainedDictGets = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (!CHAINED_DICT_GET_RE.test(lines[i])) continue;
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-chained-dict-get",
			severity: "warning",
			message: "Chained `.get(..., {})` defaults hide missing-data cases.",
			help: "Normalize the input at the boundary, use a typed object, or split the lookup into explicit steps. Empty-dict fallback chains are a common agent shortcut that becomes brittle as schemas evolve.",
		});
	}
};

const countBranchLadder = (
	lines: string[],
	start: number,
	pattern: RegExp,
	selector: string,
	indent: string,
): number => {
	let count = 1;
	for (let i = start + 1; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed === "" || trimmed.startsWith("#")) continue;
		const match = pattern.exec(line);
		if (match?.[1] === indent && match[2] === selector) {
			count++;
			continue;
		}
		if (line.startsWith(`${indent}elif `)) break;
		if (
			line.length - line.trimStart().length <= indent.length &&
			!line.startsWith(`${indent}else`)
		) {
			break;
		}
	}
	return count;
};

const flagBranchLadders = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	const reported = new Set<number>();
	for (let i = 0; i < lines.length; i++) {
		if (reported.has(i)) continue;
		const valueMatch = SAME_VALUE_BRANCH_RE.exec(lines[i]);
		if (valueMatch) {
			const count = countBranchLadder(lines, i, SAME_VALUE_BRANCH_RE, valueMatch[2], valueMatch[1]);
			if (count >= BRANCH_LADDER_THRESHOLD) {
				reported.add(i);
				pushLineFinding(out, relPath, i + 1, {
					rule: "ai-slop/python-repetitive-dispatch",
					severity: "warning",
					message: `${count} repeated branches dispatch on \`${valueMatch[2]}\`.`,
					help: "Use a table, set membership, or handler map when branches share the same shape. SlopCodeBench highlights these selector ladders as code that keeps growing instead of absorbing new cases cleanly.",
				});
			}
			continue;
		}

		const instanceMatch = INSTANCE_BRANCH_RE.exec(lines[i]);
		if (!instanceMatch) continue;
		const count = countBranchLadder(
			lines,
			i,
			INSTANCE_BRANCH_RE,
			instanceMatch[2],
			instanceMatch[1],
		);
		if (count < BRANCH_LADDER_THRESHOLD) continue;
		reported.add(i);
		pushLineFinding(out, relPath, i + 1, {
			rule: "ai-slop/python-isinstance-ladder",
			severity: "warning",
			message: `${count} repeated \`isinstance(${instanceMatch[2]}, ...)\` branches.`,
			help: "Prefer a handler map, protocol, or normalized intermediate representation when each type branch has the same role. Repeated type ladders are one of the maintainability smells SCBench-style checks look for.",
		});
	}
};

export const detectPythonPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!PY_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = path.relative(context.rootDirectory, filePath);
		const basename = path.basename(filePath);
		const lines = content.split("\n");

		flagBareExcept(lines, relPath, diagnostics);
		flagBroadExceptWithSilentBody(lines, relPath, diagnostics);
		flagMutableDefaults(lines, relPath, diagnostics);
		flagPrintInProduction(lines, relPath, basename, diagnostics);
		flagRangeLenLoops(lines, relPath, diagnostics);
		flagChainedDictGets(lines, relPath, diagnostics);
		flagBranchLadders(lines, relPath, diagnostics);
	}

	return diagnostics;
};
