import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const JS_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

const CATCH_HEAD_RE = /\bcatch\s*(?:\([^)]*\))?\s*\{/g;

// A statement that only emits a log line: console.* or <ident>.{warn,info,error,log,debug}(...).
const LOG_STATEMENT_RE =
	/^(?:console|[\w$]+(?:\.[\w$]+)*)\.(?:log|info|warn|warning|error|debug|trace)\s*\(/;

// Control-flow / handling tokens that mean the catch does more than log-and-continue.
const HANDLING_TOKEN_RE = /\b(?:throw|return|reject|next|process\.exit|continue|break)\b/;

const stripBlockComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//g, "");

const extractCatchBody = (content: string, openBraceIndex: number): string | null => {
	let depth = 0;
	let inString: string | null = null;
	for (let i = openBraceIndex; i < content.length; i += 1) {
		const ch = content[i];
		const prev = content[i - 1];
		if (inString) {
			if (ch === inString && prev !== "\\") inString = null;
			continue;
		}
		if (ch === '"' || ch === "'" || ch === "`") {
			inString = ch;
			continue;
		}
		if (ch === "{") {
			depth += 1;
		} else if (ch === "}") {
			depth -= 1;
			if (depth === 0) return content.slice(openBraceIndex + 1, i);
		}
	}
	return null;
};

// True when every statement in the body is a bare log call and nothing else.
const isLogOnlyBody = (body: string): boolean => {
	const cleaned = stripBlockComments(body);
	const statements = cleaned
		.split("\n")
		.map((line) => line.replace(/\/\/.*$/, "").trim())
		.filter((line) => line.length > 0 && line !== ";");

	if (statements.length === 0) return false; // empty catch is swallowed-exception's job.
	if (statements.some((line) => HANDLING_TOKEN_RE.test(line))) return false;

	let sawLog = false;
	for (const statement of statements) {
		// Allow trailing semicolons and a lone closing/opening artifact from multi-line calls.
		const normalized = statement.replace(/;+$/, "");
		if (LOG_STATEMENT_RE.test(normalized)) {
			sawLog = true;
			continue;
		}
		// A continuation line of a multi-line log call (arguments only) is acceptable.
		if (/^[\w$"'`{[(),.\s+:-]+$/.test(normalized) && !/[=(]\s*(?:async\s+)?\(/.test(normalized)) {
			continue;
		}
		return false;
	}
	return sawLog;
};

const detectJsSilentRecovery = (content: string, relPath: string): Diagnostic[] => {
	const out: Diagnostic[] = [];
	CATCH_HEAD_RE.lastIndex = 0;
	let match: RegExpExecArray | null;
	while ((match = CATCH_HEAD_RE.exec(content)) !== null) {
		const braceIndex = match.index + match[0].length - 1;
		const body = extractCatchBody(content, braceIndex);
		if (body === null) continue;
		if (!isLogOnlyBody(body)) continue;

		const line = content.slice(0, match.index).split("\n").length;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/silent-recovery",
			severity: "warning",
			message: "Catch only logs then continues, leaving execution in a possibly broken state",
			help: "Handle the error: rethrow, return an error value, or recover explicitly. Logging alone lets the program proceed as if nothing failed.",
			line,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return out;
};

const PY_EXCEPT_RE = /^(\s*)except\b[^\n]*:\s*(?:#.*)?$/;
const PY_LOG_STATEMENT_RE =
	/^(?:logging|logger|log|self\.log|self\.logger|print)(?:\.(?:debug|info|warning|warn|error|exception|critical))?\s*\(/;
const PY_HANDLING_TOKEN_RE = /^(?:raise\b|return\b|continue\b|break\b|self\.|[\w.]+\s*=)/;

const detectPySilentRecovery = (content: string, relPath: string): Diagnostic[] => {
	const out: Diagnostic[] = [];
	const lines = content.split("\n");

	for (let i = 0; i < lines.length; i += 1) {
		const exceptMatch = PY_EXCEPT_RE.exec(lines[i]);
		if (!exceptMatch) continue;
		const indent = exceptMatch[1].length;

		const bodyLines: string[] = [];
		let j = i + 1;
		for (; j < lines.length; j += 1) {
			const raw = lines[j];
			if (raw.trim() === "") continue;
			const lineIndent = raw.length - raw.trimStart().length;
			if (lineIndent <= indent) break;
			bodyLines.push(raw.trim());
		}

		if (bodyLines.length === 0) continue;
		if (bodyLines.some((line) => PY_HANDLING_TOKEN_RE.test(line))) continue;
		if (bodyLines.some((line) => line === "pass")) continue; // swallowed-exception's job.

		const allLogs = bodyLines.every(
			(line) => PY_LOG_STATEMENT_RE.test(line) || /^[\w"'(),.\s+:%{}[\]-]+$/.test(line),
		);
		const sawLog = bodyLines.some((line) => PY_LOG_STATEMENT_RE.test(line));
		if (!allLogs || !sawLog) continue;

		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/silent-recovery",
			severity: "warning",
			message: "except only logs then continues, leaving execution in a possibly broken state",
			help: "Handle the error: re-raise, return an error value, or recover explicitly. Logging alone lets the program proceed as if nothing failed.",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: false,
		});
	}
	return out;
};

export const detectSilentRecovery = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		const ext = path.extname(filePath);
		const isJs = JS_EXTS.has(ext);
		const isPy = ext === ".py";
		if (!isJs && !isPy) continue;

		const relPath = path.relative(context.rootDirectory, filePath);
		if (isNonProductionPath(relPath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		if (isJs) {
			diagnostics.push(...detectJsSilentRecovery(content, relPath));
		} else {
			diagnostics.push(...detectPySilentRecovery(content, relPath));
		}
	}

	return diagnostics;
};
