import {spawnSync} from "node:child_process";
import micromatch from "micromatch";
import fs from "node:fs";
import path from "node:path";
import type {EngineContext} from "../engines/types.js";

const MAX_BUFFER = 50 * 1024 * 1024;

const SOURCE_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".mjs",
	".cjs",
	".py",
	".go",
	".rs",
	".rb",
	".java",
	".php",
]);

const EXCLUDED_DIRS = [
	"node_modules",
	"dist",
	"build",
	".git",
	"vendor",
	"tests",
	"test",
	"__tests__",
	"__test__",
	"spec",
	"__mocks__",
	"fixtures",
	"test_data",
	".next",
	".nuxt",
	"coverage",
	".turbo",
];

const FIND_PRUNE_DIRS = [
	"node_modules",
	"dist",
	"build",
	".git",
	"vendor",
	".next",
	".nuxt",
	"coverage",
	".turbo",
];

const TEST_FILE_PATTERNS = [
	/(?:^|\/).*\.test\.[^/]+$/i,
	/(?:^|\/).*\.spec\.[^/]+$/i,
	/(?:^|\/)test_[^/]+\.(?:py|rb|php|js|jsx|ts|tsx|java)$/i,
	/(?:^|\/)[^/]+_test\.(?:py|go|rb|php|js|jsx|ts|tsx|java)$/i,
];

const AUTO_GENERATED_PATTERNS = [
	/auto-generated/i,
	/@generated/i,
	/DO NOT (?:EDIT|MODIFY)/i,
	/this file (?:is|was) (?:auto-?)?generated/i,
	/automatically generated/i,
	/generated by/i,
];

const toProjectPath = (rootDirectory: string, filePath: string): string => {
	const absolutePath = path.isAbsolute(filePath) ? filePath : path.resolve(rootDirectory, filePath);
	return path.relative(rootDirectory, absolutePath).split(path.sep).join("/");
};

const isWithinProject = (relativePath: string): boolean =>
	relativePath.length > 0 && !relativePath.startsWith("..");

const hasAllowedExtension = (filePath: string, extraExtensions: Set<string>): boolean => {
	const extension = path.extname(filePath);
	return SOURCE_EXTENSIONS.has(extension) || extraExtensions.has(extension);
};

const isExcludedPath = (filePath: string): boolean =>
	EXCLUDED_DIRS.some(
		(dir) => filePath === dir || filePath.startsWith(`${dir}/`) || filePath.includes(`/${dir}/`),
	);

const isTestFile = (filePath: string): boolean =>
	TEST_FILE_PATTERNS.some((pattern) => pattern.test(filePath));

const getIgnoredPaths = (rootDirectory: string, files: string[]): Set<string> => {
	if (files.length === 0) return new Set<string>();

	const result = spawnSync("git", ["check-ignore", "--no-index", "--stdin"], {
		cwd: rootDirectory,
		encoding: "utf-8",
		input: files.join("\n"),
		maxBuffer: MAX_BUFFER,
	});

	if (result.error || (result.status !== 0 && result.status !== 1)) {
		return new Set<string>();
	}

	return new Set(
		result.stdout
			.split("\n")
			.map((file) => file.trim())
			.filter((file) => file.length > 0),
	);
};

export const listProjectFiles = (rootDirectory: string): string[] => {
	const result = spawnSync("git", ["ls-files", "--cached", "--others", "--exclude-standard"], {
		cwd: rootDirectory,
		encoding: "utf-8",
		maxBuffer: MAX_BUFFER,
	});

	if (!result.error && result.status === 0) {
		return result.stdout
			.split("\n")
			.filter((file) => file.length > 0)
			.filter((file) => fs.existsSync(path.resolve(rootDirectory, file)));
	}

	const findArgs = [
		".",
		"(",
		...FIND_PRUNE_DIRS.flatMap((dir, index) =>
			index === 0 ? ["-name", dir] : ["-o", "-name", dir],
		),
		")",
		"-prune",
		"-o",
		"-type",
		"f",
		"-print",
	];
	const findResult = spawnSync("find", findArgs, {
		cwd: rootDirectory,
		encoding: "utf-8",
		maxBuffer: MAX_BUFFER,
	});

	if (findResult.error || findResult.status !== 0) return [];

	return findResult.stdout
		.split("\n")
		.filter((file) => file.length > 0)
		.map((file) => file.replace(/^\.\//, ""));
};

const normalizeExcludePatterns = (patterns: string[]): string[] => {
	return patterns.flatMap((pattern) => {
		const p = pattern.trim();
		if (p.startsWith(".")) {
			return [`**/*${p}`];
		}
		if (!p.includes("*") && !p.includes(".")) {
			return [`${p}/**`];
		}
		return [p];
	});
};

export const filterProjectFiles = (
	rootDirectory: string,
	files: string[],
	extraExtensions: string[] = [],
	exclude: string[] = [],
	include: string[] = [],
): string[] => {
	const extraSet = new Set(extraExtensions);
	const normalizedFiles = files
		.map((file) => {
			const absolutePath = path.isAbsolute(file) ? file : path.resolve(rootDirectory, file);
			const relativePath = toProjectPath(rootDirectory, absolutePath);
			return {absolutePath, relativePath};
		})
		.filter(({relativePath}) => isWithinProject(relativePath));

	const relativePaths = normalizedFiles.map(({relativePath}) => relativePath);

	const ignoredPaths = getIgnoredPaths(rootDirectory, relativePaths);
	const normalizedExcludePatterns = exclude.length ? normalizeExcludePatterns(exclude) : [];

	const isUserExcluded = (relativePath: string) => {
		if (!normalizedExcludePatterns.length) return false;
		return micromatch.isMatch(relativePath, normalizedExcludePatterns, {
			dot: true,
		});
	};

	const hasIncludePatterns = include.length > 0;

	const isUserIncluded = (relativePath: string) => {
		if (!hasIncludePatterns) return true;

		return micromatch.isMatch(relativePath, include, {
			dot: true,
		});
	};

	return normalizedFiles.filter(({absolutePath, relativePath}) => {
		if (
			!fs.existsSync(absolutePath) ||
			!isWithinProject(relativePath) ||
			isExcludedPath(relativePath) ||
			isTestFile(relativePath) ||
			ignoredPaths.has(relativePath)
		) {
			return false;
		}
		if (!isUserIncluded(relativePath)) {
			return false;
		}
		// exclude precedence over include
		if (isUserExcluded(relativePath)) {
			return false;
		}
		return hasAllowedExtension(relativePath, extraSet);
	}).map(({absolutePath}) => absolutePath);
};

const filterExplicitFiles = (
	rootDirectory: string,
	files: string[],
	extraExtensions: string[] = [],
): string[] => {
	const extraSet = new Set(extraExtensions);

	return files
		.map((file) => {
			const absolutePath = path.isAbsolute(file) ? file : path.resolve(rootDirectory, file);
			const relativePath = toProjectPath(rootDirectory, absolutePath);
			return {absolutePath, relativePath};
		})
		.filter(
			({relativePath}) =>
				isWithinProject(relativePath) && hasAllowedExtension(relativePath, extraSet),
		)
		.map(({absolutePath}) => absolutePath);
};

export const isAutoGenerated = (filePath: string): boolean => {
	let fd: number | undefined;
	try {
		fd = fs.openSync(filePath, "r");
		const buf = Buffer.alloc(512);
		const bytesRead = fs.readSync(fd, buf, 0, 512, 0);
		const header = buf.toString("utf-8", 0, bytesRead);
		return AUTO_GENERATED_PATTERNS.some((pattern) => pattern.test(header));
	} catch {
		return false;
	} finally {
		if (fd !== undefined) {
			try {
				fs.closeSync(fd);
			} catch {
				// ignore close errors
			}
		}
	}
};

export const getSourceFilesForRoot = (rootDirectory: string): string[] =>
	filterProjectFiles(rootDirectory, listProjectFiles(rootDirectory));

export const getSourceFiles = (context: EngineContext): string[] => {
	if (context.files) {
		return filterExplicitFiles(context.rootDirectory, context.files);
	}

	return getSourceFilesForRoot(context.rootDirectory);
};

export const getSourceFilesWithExtras = (
	context: EngineContext,
	extraExtensions: string[],
): string[] => {
	if (context.files) {
		return filterExplicitFiles(context.rootDirectory, context.files, extraExtensions);
	}

	return filterProjectFiles(
		context.rootDirectory,
		listProjectFiles(context.rootDirectory),
		extraExtensions,
	);
};
