// aislop-ignore-file duplicate-block
import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { countTemplateLines, findFunctionEnd, isBlockArrow } from "./function-boundaries.js";

interface FunctionInfo {
	name: string;
	startLine: number;
	lineCount: number;
	maxNesting: number;
	paramCount: number;
	templateLines: number;
}
interface FunctionPattern {
	regex: RegExp;
	langFilter: string[];
}

const FUNCTION_PATTERNS: FunctionPattern[] = [
	{
		regex: /^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"],
	},
	{
		regex: /^\s*(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s+)?\(([^)]*)\)\s*(?:=>|:\s*\w)/,
		langFilter: [".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"],
	},
	{
		regex: /^\s*def\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".py"],
	},
	{
		regex: /^\s*func\s+(?:\([^)]*\)\s+)?(\w+)\s*\(([^)]*)\)/,
		langFilter: [".go"],
	},
	{
		regex: /^\s*fn\s+(\w+)\s*\(([^)]*)\)/,
		langFilter: [".rs"],
	},
	{
		regex: /^\s*(?:public|private|protected)?\s*(?:static\s+)?(?:\w+\s+)(\w+)\s*\(([^)]*)\)/,
		langFilter: [".java", ".cs", ".cpp", ".c", ".php"],
	},
];

const countParams = (p: string): number => (p.trim() ? p.split(",").length : 0);

const matchFunctionOnLine = (
	line: string,
	ext: string,
): { name: string; params: string; patternIndex: number } | null => {
	for (let i = 0; i < FUNCTION_PATTERNS.length; i++) {
		const pattern = FUNCTION_PATTERNS[i];
		if (!pattern.langFilter.includes(ext)) continue;
		const match = line.match(pattern.regex);
		if (match) return { name: match[1], params: match[2] ?? "", patternIndex: i };
	}
	return null;
};

const isDataFile = (content: string): boolean => {
	const lines = content.split("\n");
	const nonEmpty = lines.filter((l) => l.trim().length > 0);
	if (nonEmpty.length === 0) return false;
	const dataLinePattern = /^\s*[{}[\]"']/;
	const dataLines = nonEmpty.filter((l) => dataLinePattern.test(l));
	return dataLines.length / nonEmpty.length > 0.8;
};

const TEST_PATH_RE = /(?:^|\/)(?:tests?|spec|specs|__tests__|__spec__|src\/test)\//i;
const TEST_BASENAME_RE =
	/(?:^|[/.])(?:test_[\w-]+\.(?:py|rb)|[\w-]+_(?:test|spec)\.(?:py|rb|go|rs)|[\w-]+\.(?:test|spec)\.(?:[jt]sx?|mjs|cjs)|conftest\.py|[A-Z]\w*Tests?\.(?:java|cs|php))$/;

const MIGRATION_PATH_RE = /(?:^|\/)(?:migrations?|migrate|prisma\/migrations|db\/migrate)\//i;

const FIXTURE_PATH_RE =
	/(?:^|\/)(?:__fixtures__|__snapshots__|__mocks__|fixtures?|snapshots?|seeds?|stubs?)\//i;

const GENERATED_PATH_RE =
	/(?:^|\/)(?:generated|gen|build|dist|out|target|coverage|node_modules|vendor|\.next|\.nuxt|\.svelte-kit)\//i;

const isExemptFromComplexity = (relativePath: string): boolean =>
	TEST_PATH_RE.test(relativePath) ||
	TEST_BASENAME_RE.test(relativePath) ||
	MIGRATION_PATH_RE.test(relativePath) ||
	FIXTURE_PATH_RE.test(relativePath) ||
	GENERATED_PATH_RE.test(relativePath);

const analyzeFunctions = (content: string, ext: string): FunctionInfo[] => {
	const lines = content.split("\n");
	const functions: FunctionInfo[] = [];

	for (let i = 0; i < lines.length; i++) {
		const fnMatch = matchFunctionOnLine(lines[i], ext);
		if (!fnMatch) continue;

		const isPython = fnMatch.patternIndex === 2;

		if (fnMatch.patternIndex === 1 && !isBlockArrow(lines, i)) {
			continue;
		}

		const { endLine, maxNesting } = findFunctionEnd(lines, i, isPython);
		const bodyLines = lines.slice(i + 1, endLine);
		const templateLines = isPython ? 0 : countTemplateLines(bodyLines);

		functions.push({
			name: fnMatch.name,
			startLine: i + 1,
			lineCount: endLine - i + 1,
			maxNesting,
			paramCount: countParams(fnMatch.params),
			templateLines,
		});
	}

	return functions;
};

interface QualityLimits {
	maxFunctionLoc: number;
	maxFileLoc: number;
	maxNesting: number;
	maxParams: number;
}

const FILE_LOC_MULTIPLIERS: Record<string, number> = {
	".tsx": 1.5,
	".jsx": 1.5,
	".rs": 2.5,
	".go": 1.5,
};

const DECLARATION_FILE_RE = /\.d\.ts$/i;

const fileLocBudget = (ext: string, relativePath: string, base: number): number => {
	if (DECLARATION_FILE_RE.test(relativePath)) return Number.POSITIVE_INFINITY;
	const multiplier = FILE_LOC_MULTIPLIERS[ext] ?? 1;
	return Math.ceil(base * multiplier);
};

const checkFileDiagnostics = (
	relativePath: string,
	content: string,
	limits: QualityLimits,
): Diagnostic[] => {
	const results: Diagnostic[] = [];
	const lineCount = content.split("\n").length;
	const ext = path.extname(relativePath).toLowerCase();

	if (isDataFile(content)) return results;

	const configuredMax = fileLocBudget(ext, relativePath, limits.maxFileLoc);
	if (!Number.isFinite(configuredMax)) return results;
	const triggerAt = Math.ceil(configuredMax * 1.1);

	if (lineCount > triggerAt) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/file-too-large",
			severity: "warning",
			message: `File too large (max: ${configuredMax})`,
			help: "Consider splitting this file into smaller modules",
			line: 0,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${lineCount} lines`,
		});
	}

	return results;
};

const JSX_EXTENSIONS = new Set([".tsx", ".jsx"]);
const isComponentFunction = (name: string, ext: string): boolean =>
	JSX_EXTENSIONS.has(ext) && /^[A-Z]/.test(name);

const functionLocBudget = (fn: FunctionInfo, ext: string, base: number): number => {
	if (isComponentFunction(fn.name, ext)) return Math.ceil(base * 2.0);
	if (ext === ".rs") return Math.ceil(base * 1.5);
	return base;
};

const checkFunctionDiagnostics = (
	relativePath: string,
	fn: FunctionInfo,
	limits: QualityLimits,
	ext: string,
): Diagnostic[] => {
	const results: Diagnostic[] = [];

	const fnMax = functionLocBudget(fn, ext, limits.maxFunctionLoc);
	const effectiveLineCount = fn.lineCount - fn.templateLines;
	if (effectiveLineCount > Math.ceil(fnMax * 1.1)) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/function-too-long",
			severity: "warning",
			message: `Function too long (max: ${fnMax})`,
			help: "Consider breaking this function into smaller pieces",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · ${fn.lineCount} lines`,
		});
	}

	if (fn.maxNesting > limits.maxNesting) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/deep-nesting",
			severity: "warning",
			message: `Function nested too deeply (max: ${limits.maxNesting})`,
			help: "Consider using early returns or extracting nested logic",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · depth ${fn.maxNesting}`,
		});
	}

	if (fn.paramCount > limits.maxParams) {
		results.push({
			filePath: relativePath,
			engine: "code-quality",
			rule: "complexity/too-many-params",
			severity: "warning",
			message: `Function has too many parameters (max: ${limits.maxParams})`,
			help: "Consider using an options object parameter",
			line: fn.startLine,
			column: 0,
			category: "Complexity",
			fixable: false,
			detail: `${fn.name} · ${fn.paramCount} params`,
		});
	}

	return results;
};

const checkFileComplexity = (
	filePath: string,
	rootDirectory: string,
	limits: QualityLimits,
): Diagnostic[] => {
	const relativePath = path.relative(rootDirectory, filePath);
	if (isExemptFromComplexity(relativePath)) return [];

	let content: string;
	try {
		content = fs.readFileSync(filePath, "utf-8");
	} catch {
		return [];
	}

	const ext = path.extname(filePath).toLowerCase();
	const diagnostics = checkFileDiagnostics(relativePath, content, limits);

	for (const fn of analyzeFunctions(content, ext)) {
		diagnostics.push(...checkFunctionDiagnostics(relativePath, fn, limits, ext));
	}

	return diagnostics;
};

export const checkComplexity = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const limits: QualityLimits = context.config.quality;
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		diagnostics.push(...checkFileComplexity(filePath, context.rootDirectory, limits));
	}

	return diagnostics;
};
